name: CI Pipeline

# Trigger the pipeline on push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use other OS like windows-latest or macos-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (using Adoptium distribution)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Use 'temurin' for Adoptium JDK

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run unit tests (optional, this is for testing purposes)
      - name: Run tests
        run: mvn test
